kind: project
metadata:
  name: start-codespace
  created: '2023-05-23T19:36:17.320763'
spec:
  functions:
  - url: data_prep.py
    name: data_prep
    kind: job
    image: mlrun/mlrun
    handler: breast_cancer_generator
  workflows: []
  artifacts: []
  source: ''
  desired_state: online
status:
  state: online
